name: flutter_ocr_mlkit_workshop
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0-171.0.dev

dependencies:
  camera: ^0.11.1
  flutter:
    sdk: flutter
  google_ml_kit: ^0.20.0
  image_picker: ^1.1.2
  permission_handler: ^12.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
